// <auto-generated />
namespace AgricolaData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FDLTracking_10001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FDLTracking_10001));
        
        string IMigrationMetadata.Id
        {
            get { return "202104191515079_FDLTracking_1.00.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
